version: '3.8'

services:
  jenkins:
    build:
      context: docker_jenkins/
      dockerfile: ./Dockerfile
    hostname: jenkins
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"     # Web interface
      - "50000:50000"   # Jenkins agent accsess port
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    build:
      context: docker_api/
      dockerfile: ./Dockerfile
    hostname: api
    container_name: api
    restart: always
    ports:
      - "80:80"

volumes:
  jenkins_home:
