version: "3.8"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    hostname: keycloak
    container_name: keycloak
    restart: always
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - keycloack-network
    depends_on:
      - keycloak-db
    environment:
      - KC_HOSTNAME_URL=http://localhost:8080
      - KC_HOSTNAME_ADMIN_URL=http://localhost:8080
      # - KC_HOSTNAME=localhost
      # - KC_HOSTNAME_PORT=8080
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true
      - KC_HTTP_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_PROXY=edge
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=1234
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=password
      - KC_LOG_LEVEL=DEBUG
    command:
      - "start-dev"
      - "--http-port=8080"
    volumes:
      - ./keycloak:/opt/keycloak/data

  keycloak-db:
    image: postgres:9.6
    hostname: keycloak-db
    container_name: keycloak-db
    networks:
      - keycloack-network
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keycloak
    volumes:
      - ./keycloakDB:/var/lib/postgresql/data

networks:
  keycloack-network:
    name: keycloack-network
    ipam:
      config:
        - subnet: 172.19.0.0/16

volumes:
  keycloak:
  keycloakDB:
