version: '3.8'

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=sample_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - TZ=Asia/Tokyo
    volumes:
      - ./data/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./data/mysql/conf.d:/etc/mysql/conf.d
      - ./data/mysql/log:/var/log/mysql
    networks:
      splunk-network:
        ipv4_address: 172.19.1.3

  splunk:
    image: splunk/splunk:7.0.3
    hostname: splunk
    container_name: splunk
    restart: on-failure
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_LICENSE_URI=Free
      - SPLUNK_ENABLE_LISTEN=9997
      - SPLUNK_ADD=tcp 1514
      - SPLUNK_USER=root
      - SPLUNK_PASSWORD=root
      - TZ=Asia/Tokyo
    volumes:
      - ./data/splunk/etc:/opt/splunk/etc
      - ./data/splunk/var:/opt/splunk/var
    networks:
      splunk-network:
        ipv4_address: 172.19.1.5

networks:
  splunk-network:
    name: splunk-network
    ipam:
      config:
        - subnet: 172.19.1.0/24

volumes:
  data:
