version: "3.8"

services:
  node-red:
    image: nodered/node-red
    container_name: node-red
    hostname: node-red
    volumes:
      - ./node-red:/data
    ports:
      - 1880:1880
    networks:
      - nodered-network

networks:
  nodered-network:
    name: nodered-network
    ipam:
      config:
        - subnet: 172.19.1.0/24

volumes:
  node-red: