version: "3"
services:
  mongo:
    image: mongo:4.4
    hostname: mongo
    container_name: mongo
    expose:
      - "3306"
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    networks:
      grafana-network:
        ipv4_address: 172.19.1.3

  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-gantt-panel,grafana-googlesheets-datasource,grafana-mongodb-datasource
    depends_on:
      - mongo
    networks:
      grafana-network:
        ipv4_address: 172.19.1.5

networks:
  grafana-network:
    name: grafana-network
    ipam:
      config:
        - subnet: 172.19.1.0/24