version: '3.8'

services:
  jenkins:
    build:
      context: docker_jenkins/
      dockerfile: ./Dockerfile
    hostname: jenkins
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"     # Web interface
      - "50000:50000"   # Jenkins agent accsess port
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  jenkins-agent1:
    build:
      context: docker_agent/
      dockerfile: ./Dockerfile
    hostname: jenkins-agent1
    container_name: jenkins-agent1
    restart: always
    depends_on:
      - jenkins
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=jenkins-agent1
      - JENKINS_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    volumes:
      - ./jenkins_home/workspace:/home/jenkins/workspace

  jenkins-agent2:
    build:
      context: docker_agent/
      dockerfile: ./Dockerfile
    hostname: jenkins-agent2
    container_name: jenkins-agent2
    restart: always
    depends_on:
      - jenkins
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=jenkins-agent2
      - JENKINS_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    volumes:
      - ./jenkins_home/workspace:/home/jenkins/workspace

volumes:
  jenkins_home:
