version: "3.8"
services:
  mysql:
    image: mysql:5.7
    container_name: 'mysql'
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=sample_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - TZ=Asia/Tokyo
    volumes:
      - ./data/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./data/mysql/conf.d:/etc/mysql/conf.d
      - ./data/mysql/log:/var/log/mysql
    networks:
      grafana-network:
        ipv4_address: 172.19.1.3

  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-gantt-panel,grafana-googlesheets-datasource,grafana-mongodb-datasource,marcusolsson-json-datasource
      - TZ=Asia/Tokyo
    depends_on:
      - mysql
    networks:
      grafana-network:
        ipv4_address: 172.19.1.5

networks:
  grafana-network:
    name: grafana-network
    ipam:
      config:
        - subnet: 172.19.1.0/24